// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlbjzxrjagzxqlunomix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsYmp6eHJqYWd6eHFsdW5vbWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDc3OTgsImV4cCI6MjA3MjIyMzc5OH0.uxTGGGW0ugp-rOGSaGZlw59PrEjPnK6m7a4L2JHqX6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});